### ISSUE TITLE
dbus.(*Conn).Auth errors

### ISSUE THREAD

**Issue by probonopd** [probonopd/go-appimage#10]
Getting

```
panic: runtime error: slice bounds out of range [2:1]

goroutine 20 [running]:
github.com/godbus/dbus.(*Conn).inWorker(0xc000104200)
        /home/me/go/pkg/mod/github.com/godbus/dbus@v4.1.0+incompatible/conn.go:355 +0xefe
created by github.com/godbus/dbus.(*Conn).Auth
        /home/me/go/pkg/mod/github.com/godbus/dbus@v4.1.0+incompatible/auth.go:118 +0x621
```

Restarting appimaged usually resolves this.

**Comment by probonopd** [comment]
Fixed
