### ISSUE TITLE
appimaged wrap - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by soulflyman** [probonopd/go-appimage#127]
Since a few days I can't start appimages from my system application menu (Kubuntu 20.04). I don't now what happened or what I did that it doesn't work any more.
When running the command that is called when the .desktop files are executed I get the following error:
```
$ ./appimaged-640-x86_64.AppImage wrap Bitwarden-1.24.6-x86_64.AppImage 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x535d8f]

goroutine 10 [running]:
gopkg.in/ini%2ev1.(*File).SectionsByName(0x0, 0xa81196, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0)
	gopkg.in/ini.v1@v1.62.0/file.go:150 +0x6f
gopkg.in/ini%2ev1.(*File).GetSection(...)
	gopkg.in/ini.v1@v1.62.0/file.go:137
gopkg.in/ini%2ev1.(*File).Section(0x0, 0xa81196, 0xd, 0x0)
	gopkg.in/ini.v1@v1.62.0/file.go:169 +0x45
main.findDesktopFilesPointingToExecutable(0x7ffc7fb7d285, 0x20, 0x0, 0x0, 0x0, 0xc0000106a8, 0x0)
	github.com/probonopd/go-appimage/src/appimaged/appwrapper.go:158 +0x32b
main.checkDesktopFiles(0x7ffc7fb7d285, 0x20)
	github.com/probonopd/go-appimage/src/appimaged/appwrapper.go:172 +0x3c
created by main.appwrap
	github.com/probonopd/go-appimage/src/appimaged/appwrapper.go:36 +0x13c
```

I don't know what's the problem or how I can find out more about what's going wrong.

**Comment by soulflyman** [comment]
Problem still exists with appimaged-646-x86_64.AppImage :(

**Comment by soulflyman** [comment]
Testet with appimaged-1-x86_64-revised-on-2021-09-16T13-00-27.AppImage and it is working now, don't know what it fixed, but tanks for fixing it.
