### ISSUE TITLE
Crash when running appimagetool in git repository without a single commit

### ISSUE THREAD

**Issue by srevinsaju** [probonopd/go-appimage#62]
```bash
❯ ../appimagetool-551-x86_64.AppImage AppDir

appimagetool-551-x86_64.AppImage 551

2020/08/25 19:36:06 git root: /home/srevinsaju/repo/scrcpy-test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x83a31a]

goroutine 1 [running]:
main.GenerateAppImage(0x7ffe9a8d9e2d, 0x6)
        github.com/probonopd/go-appimage/src/appimagetool/appimagetool.go:264 +0x44da
main.main()
        github.com/probonopd/go-appimage/src/appimagetool/appimagetool.go:217 +0x912
```
~~Well,I do not know what happened~~ See https://github.com/probonopd/go-appimage/issues/62#issuecomment-680141958 .

**Comment by srevinsaju** [comment]
Reproducer:
```
mkdir test
cd test
mkdir AppDir
touch AppDir/AppRun
git init
appimagetool*.AppImage AppDir
```

possibly because no commits have been found

**Comment by probonopd** [comment]
Confirmed.

Without `git init`, the error does not happen:

```
me@host:~/test$ ./appimagetool-551-x86_64.AppImage AppDir/

appimagetool-551-x86_64.AppImage 551

2020/08/25 20:39:35 Apparently not in a git repository
Version not found, aborting. Set it with VERSION=... ./appimagetool-551-x86_64.AppImage
```

With git init but no commits the error does happen:

```
me@host:~/test$ git init
Initialized empty Git repository in /home/me/test/.git/
me@host:~/test$ ./appimagetool-551-x86_64.AppImage AppDir/

appimagetool-551-x86_64.AppImage 551

2020/08/25 20:39:41 git root: /home/me/test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x83a31a]

goroutine 1 [running]:
main.GenerateAppImage(0x7ffca34733ff, 0x6)
	github.com/probonopd/go-appimage/src/appimagetool/appimagetool.go:264 +0x44da
main.main()
	github.com/probonopd/go-appimage/src/appimagetool/appimagetool.go:217 +0x912
```

Committing something makes the error go away:

```
me@host:~/test$ git add AppDir/
me@host:~/test$ git commit -m "Initial commit"
[master (root-commit) d1b1504] Initial commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 AppDir/AppRun
me@host:~/test$ ./appimagetool-551-x86_64.AppImage AppDir/

appimagetool-551-x86_64.AppImage 551

2020/08/25 20:40:20 git root: /home/me/test
2020/08/25 20:40:20 NOTE: Using d1b1504 from 'git rev-parse --short HEAD' as the version
2020/08/25 20:40:20       Please set the $VERSION environment variable if this is not intended
No top-level desktop file found in AppDir, aborting
```

**Comment by probonopd** [comment]
Turns out I am checking `err` which the call directly before does not even return...

https://github.com/probonopd/go-appimage/blob/1d3650c640e4605b36e0b9d2a3569a2ec01ab71d/src/appimagetool/appimagetool.go#L264-L267

What is the correct way of doing this? (In Python, I would wrap this in try.. except...)

**Comment by srevinsaju** [comment]
Hmm, yea. I am not sure of how to handle this in `go`. 

What does `gitHead.Hash()` give? I guess indexing a `null` instance raises an error, as the same thing would have happened in Python too...

**Comment by probonopd** [comment]
That did not do the trick yet.

**Comment by probonopd** [comment]
The experiment at https://play.golang.org/p/1gYa2ANgpWi shows that

```
package main

import (
	"fmt"
)

func main() {
	myString := "1234567890"
	shortString := myString[:7]
	fmt.Println(shortString)
	
	myString2 := "123"
	shortString2 := myString2[:7]
	fmt.Println(shortString2)
	
}
```

results in a different crash, namely a `panic: runtime error: slice bounds out of range [:7] with length 3` whereas we are getting a `panic: runtime error: invalid memory address or nil pointer dereference`. So checking the length of the string before trying to get the 7 characters wouldn't cut it for us - it's likely calling `gitHead.Hash()` which produces the crash. But how can I catch that error given that `gitHead.Hash()` does not return `err`?
